### ISSUE TITLE
language menu is empty

### ISSUE THREAD

**Issue by mosaferkarbala** [JasonBaier/ci3-fire-starter#21]
hi, 
i appreciate ur effort on this project, i installed its really good but i have a problem on my local machine with it that as i mentioned in title the language menu is empty in the top nav bar and in the profile menu. i add core language of codeigniter and it didn't change. please tell me if im wrong or ots a bug in the fire-starter.
here is two screenshot may be help:
http://i63.tinypic.com/mw65hd.jpg
http://i65.tinypic.com/1z4z8tc.jpg

--update:
by the way now i checked ihe log and it saids:
ERROR - 2016-01-06 22:18:46 --> Severity: Notice --> Array to string conversion C:\xampp\application\core\MY_Lang.php 82
ERROR - 2016-01-06 22:18:46 --> Severity: Notice --> Array to string conversion C:\xampp\application\core\MY_Lang.php 102
ERROR - 2016-01-06 22:18:46 --> Severity: Notice --> Array to string conversion C:\xampp\application\core\MY_Lang.php 144

thanks a lot
sincerely
bye

**Comment by ghost** [comment]
Replace <b>if(substr($language, -1) == '/')</b> with <b>if(substr($language, -1) == '/' || substr($language, -1) == '\')</b> or <b>if(in_array(substr($language, -1), ['/', '\']))</b> in core_helper.php line 220 if you're local machine is a windows!

**Comment by JasonBaier** [comment]
@Everterstraat 's fix has been included in version 3.2.3.
