### ISSUE TITLE
Database

### ISSUE THREAD

**Issue by mrtn** [JasonBaier/ci3-fire-starter#22]
Hi,

I think the database isn't updated yet. While setting up i get the following error.

Error Number: 1146
Table 'firestarter.login_attempts' doesn't exist
DELETE FROM login_attempts WHERE attempt < '2016-03-02 10:36:35'
Filename: models/Users_model.php
Line Number: 425

Can you upload it?

**Comment by JasonBaier** [comment]
Thanks, I did forget. You could also just run the schema update, but I uploaded an updated master SQL file.
