### ISSUE TITLE
Object not found! Error 404

### ISSUE THREAD

**Issue by adyoi** [JasonBaier/ci3-fire-starter#26]
After i change $config['base_url'] and do login page not found

I use Ci 3.1.0

**Comment by JasonBaier** [comment]
That could be any number of problems: 1) a simple typo in you config setting, 2) not having your vhost configured properly, 3) incorrect web root path in the core config file. 

I suspect it may be #2. Make sure you include /htdocs appended to your vhost path. I would need more specific details about your setup to be able to help more.

For your reference, here is the setup instructions provided by CodeIgniter: http://www.codeigniter.com/user_guide/installation/index.html, and here is the setup instructions for the application: http://jasonbaier.github.io/ci3-fire-starter/#installation.

**Comment by JasonBaier** [comment]
@adyoi, were you able to get this working? Check out this similar post: https://github.com/JasonBaier/ci3-fire-starter/issues/29#issuecomment-253049578.
