### ISSUE TITLE
log_message function not working.

### ISSUE THREAD

**Issue by karlgray** [JasonBaier/ci3-fire-starter#27]
None of my log_messages was working in any controller extended from My_Controller.  The system messages and anything extending CI_Controller worked fine.

I tracked it down to this line in the My_Controller constructor.

date_default_timezone_set($timezones[$this->settings->timezones]);

I checked in the config and my time_reference configuration was;

  $config['time_reference'] = 'local';

Once I set it to a UM?  value the log_message function started working again ok.

Not sure why this is the case,  but posting here as an informational.

**Comment by JasonBaier** [comment]
Thanks for the info. I'll see if I can find more on this.
