### ISSUE TITLE
Email Validation Error

### ISSUE THREAD

**Issue by dink** [JasonBaier/ci3-fire-starter#28]
Every instance of a form throws up a error

`The Email field must contain a valid email address.`

and it comes down to this validation rule: `valid_email`

Anyone else having this problem?

**Comment by JasonBaier** [comment]
Are you referring to the Contact form? I can not replicate this issue when entering a valid email address.

**Comment by JasonBaier** [comment]
Since I can not replicate, I am closing this issue. Please reopen if you can provide more specific information on how to reproduce.
