### ISSUE TITLE
Installation problem

### ISSUE THREAD

**Issue by alkyu92** [JasonBaier/ci3-fire-starter#29]
I installed apache2 on my ubuntu 16 and the localhost folder is located in /var/www/html/

Downloaded ci3-fire-starter and extracted the folder to /var/www/html/ci3-fire-starter-folder

I also followed the installation instruction; changing the base url to => http://localhost/ci3-fire-starter-folder
configured the database, gives permission to the folder and so on

However, I only managed to view the welcome page. But once I click on login button or contact or whatever, I got an error

is there any step(s) that I missed? Please help me

**Comment by mrtn** [comment]
What error is shown? 404?

**Comment by alkyu92** [comment]
Yeah.

The 404 page not found error

**Comment by ayubDev** [comment]
me too , I think this problem because of .htaccess !!!

**Comment by alkyu92** [comment]
Did you solved the problem with .htaccess ?

**Comment by ayubDev** [comment]
I found an other solution is to add htdocs in your Base_url 
Exp : 
$config['base_url'] = 'http://localhost/lab/ci3/htdocs';

**Comment by alkyu92** [comment]
@ayubDev 

its not working for me

**Comment by alkyu92** [comment]
@JasonBaier 

can you review this issue?

**Comment by JasonBaier** [comment]
It sounds like you have 1 of 2 possible issues:

1) If you're using localhost without virtualhosts, localhost usually only points to /var/www/. But you have a sub folder called /html/, so your URL should be http://localhost/html/ci3-fire-starter-folder. That should be line 26 in config.php. Then the core.php 'root_folder' setting should be 'htdocs' (default), unless you've changed the folder name.

2) If you're not using virtualhosts, I suggest using them. You can search for how to do that based on your development environment. There are plenty of blog posts out there on how to configure vhosts for XAMPP, Mac, Ubuntu and WAMP. Here's a helpful article on how to do it in Ubuntu: http://www.itzgeek.com/how-tos/linux/ubuntu-how-tos/setup-apache-virtual-hosts-on-ubuntu-15-04-14-04.html#virtualhosts. They use .local extensions in their examples; I prefer .dev extensions.

Let me know if you get it working after trying either of these.

**Comment by alkyu92** [comment]
@JasonBaier 
Hey!

The solution 2) worked for me! I tried on WAMP and everything fine. Maybe there is some misconfiguration on my ubuntu's Apache server.

Thank you very much for the help everybody!
