### ISSUE TITLE
can't add composer packet

### ISSUE THREAD

**Issue by satrioaw** [JasonBaier/ci3-fire-starter#31]
I trying add composer packet

https://github.com/raveren/kint/

with

`composer require raveren/kint`

and I already enable in application/config/config.php

with

`$config['composer_autoload'] = TRUE;`

but when I load the application this composer packet aren't work and another packet I add on from composer, any suggestion or idea ?

and downloaded packet not in 

/application/vendor 

but in main folder,

i made solution this

https://github.com/JasonBaier/ci3-fire-starter/pull/32

maybe you have another good solution

**Comment by JasonBaier** [comment]
CI 3 is supposed to have this handled in the $config['composer_autoload'] setting (https://www.codeigniter.com/user_guide/general/autoloader.html). I believe the article you referenced applies only to CI 2 or older. Closing.
