### ISSUE TITLE
Admin template footer bug

### ISSUE THREAD

**Issue by Snipees** [JasonBaier/ci3-fire-starter#34]
Hello,

I noticed some bugs with the admin template:

1. The footer always produces a vertical scrollbar, even if the content of the page is less than the height of the screen. (eg. the admin dashboard)
There are approximately 10 white pixels below the footer's banner.

2. Regarding issue #29, if I'm not using a vhost, the footer is set at the height of the screen (not below content of the page)
If the page content is greater than the height of the screen, the footer is displayed over the content. For example, in the "Settings" page, the footer is fixed at the "Welcome Message" heading, even if I scroll down, the footer remains fixed. (on my fullhd screen)

Also, if I'm not using a vhost, the language button does not work and returns a system dialog box that displays message "404 not found".
However, changing the language in the user profile work smoothly.

Tested with latest Chrome and Firefox.

**Comment by JasonBaier** [comment]
Fixed in release 3.3.2 on 12/14/2016.
