### ISSUE TITLE
CRUD in propject

### ISSUE THREAD

**Issue by doctoroakin** [JasonBaier/ci3-fire-starter#38]
Hello - Just wanted to say that I really like this project.  I noticed you have CRUD functionality built into the admin area.  Did you use a framework to do that?

Have you ever though about incorporating GroceryCRUD into this project? I tried to do it, but was not successful. If you were ever thinking about features, incorporating GroceryCRUD into this started app would be awesome!.

**Comment by JasonBaier** [comment]
I am familiar with GroceryCRUD, but opted not to use it because the purpose of this project is to demonstrate how to build an application using vanilla CodeIgniter.
